<?php

$labels = array();
$labels['preference'] = 'Antwortadresse (Custom from)';
$labels['preference_compose'] = 'Benutzerdefinierte Adresse beim Beantworten einer E-Mail';
$labels['preference_compose_contains'] = '...und Empfängeradresse enthält';
$labels['preference_compose_identity'] = 'Name und Signatur der Identität verwenden';
$labels['preference_compose_identity_exact'] = 'wenn die Adresse genau übereinstimmt';
$labels['preference_compose_identity_loose'] = 'immer';
$labels['preference_compose_subject'] = 'Aktivieren, wenn eine meiner Identitäten';
$labels['preference_compose_subject_always'] = 'Immer die Standardidentität aktivieren';
$labels['preference_compose_subject_domain'] = 'dieselbe Domain wie einer der Empfänger verwendet';
$labels['preference_compose_subject_exact'] = 'einer der Empfänger ist';
$labels['preference_compose_subject_never'] = 'Nie automatisch aktivieren';
$labels['preference_compose_subject_prefix'] = 'einer der Empfänger ist mit +Suffix';
$labels['custom_from_off'] = 'Identität auswählen';
$labels['custom_from_off_hint'] = 'Absender aus Liste auswählen';
$labels['custom_from_on'] = 'Frei wählbare Identität';
$labels['custom_from_on_hint'] = 'Absender manuell eingeben';
