<?php

$labels = array();
$labels['preference'] = 'Antwortadresse (Custom From)';
$labels['preference_compose'] = 'Benutzerdefinierte Adresse beim Antworten auf eine E-Mail';
$labels['preference_compose_contains'] = '...und Empfängeradresse enthält;
$labels['preference_compose_identity'] = 'Verwenden Sie den Namen und die Unterschrift der Identität';
$labels['preference_compose_identity_exact'] = 'Wenn die Adresse genau übereinstimmt';
$labels['preference_compose_identity_loose'] = 'Stets';
$labels['preference_compose_subject'] = 'Aktivieren, wenn ein Empfänger';';
$labels['preference_compose_subject_always'] = 'Immer mit Standardidentität aktivieren';
$labels['preference_compose_subject_domain'] = 'Verwendet dieselbe Domäne wie einer der Empfänger';
$labels['preference_compose_subject_exact'] = 'Ist einer der Empfänger';
$labels['preference_compose_subject_never'] = 'Niemals automatisch aktivieren';
$labels['preference_compose_subject_prefix'] = 'Ist einer der Empfänger mit dem Suffix +';
$labels['custom_from_off'] = 'Identität auswählen';
$labels['custom_from_off_hint'] = 'Absender aus Liste auswählen';
$labels['custom_from_on'] = 'Frei wählbare Identität';
$labels['custom_from_on_hint'] = 'Absender manuell eingeben';
