<?php

$labels = array();
$labels['preference'] = 'Antwortadresse (Custom From)';
$labels['preference_compose'] = 'Benutzerdefinierte Adresse beim Antworten auf eine E-Mail';
$labels['preference_compose_contains'] = '...und enthält Text (optional)';
$labels['preference_compose_identity'] = 'Verwenden Sie Parameter dieser Identität';
$labels['preference_compose_identity_always'] = 'Ja (Namen, Unterschrift usw. verwenden.)';
$labels['preference_compose_identity_never'] = 'Nein (Verwenden Sie eine leere Identität)';
$labels['preference_compose_subject'] = 'Aktivieren, wenn ein Empfänger';
$labels['preference_compose_subject_always'] = 'Immer automatisch aktivieren';
$labels['preference_compose_subject_domain'] = 'Verwendet dieselbe Domäne wie eine Identität';
$labels['preference_compose_subject_exact'] = 'Ist genau eine meiner Identitäten';
$labels['preference_compose_subject_never'] = 'Niemals automatisch aktivieren';
$labels['preference_compose_subject_prefix'] = 'Ist eine meiner Identitäten mit +Suffix';
$labels['custom_from_off'] = 'Identität auswählen';
$labels['custom_from_off_hint'] = 'Absender aus Liste auswählen';
$labels['custom_from_on'] = 'Frei wählbare Identität';
$labels['custom_from_on_hint'] = 'Absender manuell eingeben';
