<?php

$labels = array();
$labels['preference'] = 'Reply address (Custom From)';
$labels['preference_compose'] = 'Custom address when replying to an e-mail';
$labels['preference_compose_contains'] = '...and contains text (optional)';
$labels['preference_compose_subject'] = 'Enable when one recipient';
$labels['preference_compose_subject_always'] = 'Always enable automatically';
$labels['preference_compose_subject_domain'] = 'Uses same domain than an identity';
$labels['preference_compose_subject_exact'] = 'Is one of my identities';
$labels['preference_compose_subject_never'] = 'Never enable automatically';
$labels['custom_from_off'] = 'Select identity';
$labels['custom_from_off_hint'] = 'Select sender from identities list';
$labels['custom_from_on'] = 'Custom identity';
$labels['custom_from_on_hint'] = 'Enter sender manually';
