<?php

$labels = array();
$labels['custom_from_off'] = 'Select identity';
$labels['custom_from_off_hint'] = 'Select sender from identities list';
$labels['custom_from_on'] = 'Custom identity';
$labels['custom_from_on_hint'] = 'Enter sender manually';
$labels['reply_settings_title'] = 'Reply settings';
$labels['reply_from_setting_label'] = 'Reply from';
$labels['reply_from_receiving_email'] = 'Receiving email address';
$labels['reply_from_receiving_email_with_identity'] = 'Receiving email address with matching identity';
$labels['reply_from_receiving_email_with_default_identity'] = 'Receiving email address with default identity';
$labels['reply_from_default_identity'] = 'Default identity';
$labels['custom_from_session_section_title'] = 'Custom_from plugin options';
