<?php

$labels = array();
$labels['preference'] = 'Reply address (Custom From)';
$labels['preference_compose'] = 'Custom address when replying to an e-mail';
$labels['preference_compose_contains'] = '...and recipient address contains';
$labels['preference_compose_identity'] = 'Use identity\'s name and signature';
$labels['preference_compose_identity_exact'] = 'If address matches exactly';
$labels['preference_compose_identity_loose'] = 'Always';
$labels['preference_compose_subject'] = 'Enable when one of my identities';
$labels['preference_compose_subject_always'] = 'Always enable with default identity';
$labels['preference_compose_subject_domain'] = 'Uses same domain than one of recipients';
$labels['preference_compose_subject_exact'] = 'Is one of the recipients';
$labels['preference_compose_subject_never'] = 'Never enable automatically';
$labels['preference_compose_subject_prefix'] = 'Is one of recipients with +suffix';
$labels['custom_from_off'] = 'Select identity';
$labels['custom_from_off_hint'] = 'Select sender from identities list';
$labels['custom_from_on'] = 'Custom identity';
$labels['custom_from_on_hint'] = 'Enter sender manually';
