<?php

$labels = array();
$labels['preference'] = 'Adresse de réponse (Custom From)';
$labels['preference_compose'] = 'Adresse personnalisée en réponse à un e-mail';
$labels['preference_compose_subject'] = 'Activer quand l\'un des destinataires';
$labels['preference_compose_subject_always'] = 'Toujours activer automatiquement';
$labels['preference_compose_subject_domain'] = 'Utilise le même domaine qu\'une identité';
$labels['preference_compose_subject_exact'] = 'Est l\'une de mes identités';
$labels['preference_compose_subject_never'] = 'Ne jamais activer automatiquement';
$labels['custom_from_off'] = 'Choisir l\'identité';
$labels['custom_from_off_hint'] = 'Choisir l\'expéditeur dans la liste des identités';
$labels['custom_from_on'] = 'Identité libre';
$labels['custom_from_on_hint'] = 'Définir l\'expéditeur manuellement';
