<?php

$labels = array();
$labels['preference'] = 'Adresse de réponse (Custom From)';
$labels['preference_compose'] = 'Adresse personnalisée en réponse à un e-mail';
$labels['preference_compose_contains'] = '...et l\'adresse du destinataire contient';
$labels['preference_compose_identity'] = 'Utiliser nom et signature de l\'identité';
$labels['preference_compose_identity_exact'] = 'Si l\'adresse correspond exactement';
$labels['preference_compose_identity_loose'] = 'Toujours';
$labels['preference_compose_subject'] = 'Activer si l\'une de mes identités';
$labels['preference_compose_subject_always'] = 'Toujours activer avec l\'identité par défaut';
$labels['preference_compose_subject_domain'] = 'Utilise le domaine d\'un des destinataires';
$labels['preference_compose_subject_exact'] = 'Est parmis les destinataires';
$labels['preference_compose_subject_never'] = 'Ne jamais activer automatiquement';
$labels['preference_compose_subject_prefix'] = 'Est l\'un des destinataires avec +suffixe';
$labels['custom_from_off'] = 'Choisir l\'identité';
$labels['custom_from_off_hint'] = 'Choisir l\'expéditeur dans la liste des identités';
$labels['custom_from_on'] = 'Identité libre';
$labels['custom_from_on_hint'] = 'Définir l\'expéditeur manuellement';
